version: '3.3'

services:
  app:
    container_name: app_api
    restart: always
    build:
      context: .
      dockerfile: Dockerfile.app
    network_mode: 'host'
  db:
    container_name: app_db
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: camels
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    network_mode: host
